# Generated by Django 2.0.6 on 2020-02-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('org', models.CharField(blank=True, max_length=20, null=True)),
                ('publish_time', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=50, null=True)),
                ('sale', models.IntegerField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('word_number', models.IntegerField(blank=True, null=True)),
                ('print_time', models.DateField(blank=True, null=True)),
                ('book_size', models.IntegerField(blank=True, null=True)),
                ('page_quality', models.CharField(blank=True, max_length=20, null=True)),
                ('book_number', models.CharField(blank=True, max_length=20, null=True)),
                ('editor_recommend', models.TextField(blank=True, null=True)),
                ('content_recommend', models.TextField(blank=True, null=True)),
                ('author_brief', models.TextField(blank=True, null=True)),
                ('list', models.TextField(blank=True, null=True)),
                ('media_comment', models.TextField(blank=True, null=True)),
                ('online_read', models.TextField(blank=True, null=True)),
                ('print_count', models.IntegerField(blank=True, null=True)),
                ('package', models.CharField(blank=True, max_length=10, null=True)),
                ('is_suit', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 't_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_category',
                'managed': False,
            },
        ),
    ]
